apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shporaai-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/StillNotEnough/shpora-ai-orchestrator-prod.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: shporaai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true